FROM centos:8 as magento

COPY ./preinstall.sh /scripts/
ADD conf/supervisord.conf /etc/supervisord.conf

RUN pwd && bash /scripts/preinstall.sh; \
cd ~; \
wget https://github.com/Genaker/Magento-AWS-Linux-2-Installation/archive/refs/heads/master.zip; \
unzip master.zip && cd ./Magento-AWS-Linux-2-Installation-master/; 

RUN set -x; \
cd ~; \
cd ./Magento-AWS-Linux-2-Installation-master/; \
ls; \
echo "Installing Utilities \n"; \
bash ./install-prepare.sh; \ 
echo "Install SupervisorDd";\
yum install epel-release -y;\
yum install supervisor -y;\
mkdir -p /var/log/supervisor;

RUN echo "Install PHP \n"; \
pwd; \
cd ~; \
ls; \
cd ./Magento-AWS-Linux-2-Installation-master/; \
bash ./install-php.sh; \
#Some bug 
yum install php-fpm -y; \
bash ./configure-php.sh; \
# bash ./install-tideways-profiler.sh
set +e; \
bash ./install-composer.sh; \
composer clear-cache; \
set -e; \
echo "Install NGINX \n"; \
bash ./install-nginx.sh; \
echo "Configure Nginx \n"; \
set +e; \
bash ./configure-nginx.sh; \
set -e; \

echo "Install Magento Git \n"; \
mkdir -p /var/www/html/magento/; \
echo "We are not instaling magento for now"; \
yum clean all && \
rm -rf /var/cache/yum; \
#bash ./install-monorepo-git.sh; 
export IP=127.0.0.1; \
set +e; \
bash ./install-magento-git.sh; \
set -e; 
ENV DOCKER=YES
EXPOSE 80 8080 443
VOLUME ["/var/www/html/shared"]
# VOLUME ["/var/www/html/magento/pub/media"]

# ENTRYPOINT ["/usr/sbin/init"]
CMD ["exec /usr/bin/supervisord -n -c /etc/supervisord.conf"]
